version: '3'
services:
  nginx:
    image: nginx:1.13.8
    container_name: nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./:/var/www/shortener
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    build:
      context: ./docker/php
    container_name: php
    links:
      - mysql
    ports:
    - 9000:9000
    volumes:
    - ./:/var/www/shortener
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    #- ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
